### ISSUE TITLE
Attempt to read property "modal" on null

### ISSUE THREAD

**Issue by DeseDere** [hooshid/rottentomatoes-scraper#2]
I get the following errors with the new update:

`Warning: Attempt to read property "modal" on null in /html/vendor/hooshid/rottentomatoes-scraper/src/Rottentomatoes.php on line 144

Warning: Attempt to read property "audienceScoreAll" on null in /html/vendor/hooshid/rottentomatoes-scraper/src/Rottentomatoes.php on line 144

Warning: Attempt to read property "value" on null in /html/vendor/hooshid/rottentomatoes-scraper/src/Rottentomatoes.php on line 144

Warning: Attempt to read property "modal" on null in /html/vendor/hooshid/rottentomatoes-scraper/src/Rottentomatoes.php on line 145

Warning: Attempt to read property "audienceScoreAll" on null in /html/vendor/hooshid/rottentomatoes-scraper/src/Rottentomatoes.php on line 145

Warning: Attempt to read property "ratingCount" on null in /html/vendor/hooshid/rottentomatoes-scraper/src/Rottentomatoes.php on line 1451`

Old versions doesen't seem to work either

**Comment by arkamali** [comment]
hi
Rottentomatoes UI changes cause this errors,
i update codes and release new version,
update package version to 2.2.2
